from Funciones_V2  import *
from tkinter import ttk
from tkinter import *
from functools import partial
ruta_base = "archivo_bd.txt"
ruta_sector = "archivo_sector_jarabe.txt"

ventana = Tk()
ventana.protocol("WM_DELETE_WINDOW", lambda:cerrar(ventana))
ventana.geometry("1300x650")
tab_control = ttk.Notebook(ventana, width=1000, height=650)
tab_control.place(x=0, y=0, relheight=1, relwidth=1)
pestaña_nucleos = ttk.Frame(tab_control, borderwidth=10, relief="solid")
pestaña_nucleos.place(x=0, y=0, relheight=1, relwidth=1)
pestaña_macro = ttk.Frame(tab_control, borderwidth=10, relief="solid")
pestaña_macro.place(x=0, y=0, relheight=1, relwidth=1)
pestaña_carga = ttk.Frame(tab_control, borderwidth=10, relief="solid")
pestaña_carga.place(x=0, y=0, relheight=1, relwidth=1)
pestaña_config = ttk.Frame(tab_control, borderwidth=10, relief="solid")
pestaña_config.place(x=0, y=0, relheight=1, relwidth=1)
tab_control.add(pestaña_nucleos, text="Preparacion de Nucleos")
tab_control.add(pestaña_macro, text="Carga de Macro")
tab_control.add(pestaña_carga, text="Carga de Batch")
tab_control.add(pestaña_config, text="Configuracion")
frame = ttk.Frame(pestaña_nucleos, borderwidth=10, relief="solid")
frame.place(x=0, y=0, relheight=0.45, relwidth=1)
frame2 = ttk.Frame(pestaña_nucleos, relief="solid", borderwidth=10)
frame2.place(x=0, rely=0.45, relheight=0.1, relwidth=1)
frame3 = ttk.Frame(pestaña_nucleos, relief="solid", borderwidth=10)
frame3.place(x=0, rely=0.55, relheight=0.45, relwidth=1)
frame_macro = ttk.Frame(pestaña_macro, borderwidth=10, relief="solid")
frame_macro.place(x=0, y=0, relheight=0.45, relwidth=1)
frame_macro2 = ttk.Frame(pestaña_macro, relief="solid", borderwidth=10)
frame_macro2.place(x=0, rely=0.45, relheight=0.1, relwidth=1)
frame_macro3 = ttk.Frame(pestaña_macro, relief="solid", borderwidth=10)
frame_macro3.place(x=0, rely=0.55, relheight=0.45, relwidth=1)
frame_config = ttk.Frame(pestaña_config, borderwidth=10)
frame_config.place(relheight=1, relwidth=1)

label_contraseña = ttk.Label(frame_config, text="Contraseña")
entrada_contraseña = ttk.Entry(frame_config, width= 30,show="*")
label_contraseña_bal = ttk.Label(frame_config, text="Contraseña Balanza")
entrada_contraseña_bal = ttk.Entry(frame_config, width= 30,show="*")
label_contraseña.place(relx=0.05, rely=0.01)
entrada_contraseña.place(relx=0.27, rely=0.01)

label_contraseña_bal.place(relx=0.05, rely=0.3)
entrada_contraseña_bal.place(relx=0.27, rely=0.3)
label_ruta_bd = ttk.Label(frame_config, text="Ruta al Archivo de Lotes             ")
entrada_ruta_bd = ttk.Entry(frame_config, width=80)
label_puerto_chico = ttk.Label(frame_config, text="Puerto Balanza Chica             ")
label_puerto_chico.place(relx=0.05, rely=0.7)
label_puerto_grande = ttk.Label(frame_config, text="Puerto Balanza Grande             ")
label_puerto_grande.place(relx=0.05, rely=0.8)
entrada_puerto_chico = ttk.Entry(frame_config, width=20)
entrada_puerto_grande = ttk.Entry(frame_config, width=20)
entrada_ruta_bd.place(relx=0.27, rely=0.14)
entrada_puerto_chico.place(relx=0.27, rely=0.7)
entrada_puerto_grande.place(relx=0.27, rely=0.8)
boton_ruta_bd = ttk.Button(frame_config, text="Config. Ruta", command=lambda:selecionar_ruta(entrada_ruta_bd,ruta_base,ruta_sector,sele_sector))
boton_ruta_bd.place(relx=0.8, rely=0.14)
desactivar_balanza_chica = Button(frame_config, text="Act./Desc. Balaza",command=lambda: des_balanza("chica",desactivar_balanza_chica,des_balanza_grande,cantidad_pesar))
desactivar_balanza_chica.place(relx=0.5, rely=0.7)
des_balanza_grande = Button(frame_config, text="Act./Desc. Balaza", command=lambda: des_balanza("grande",desactivar_balanza_chica,des_balanza_grande,cantidad_pesar))
des_balanza_grande.place(relx=0.5, rely=0.8)
boto_autenticar_bal = ttk.Button(frame_config, text="Autenticar Balanza", command=partial(autenticar_balanza,entrada_contraseña_bal,des_balanza_grande,desactivar_balanza_chica))
boto_autenticar_bal.place(relx=0.8, rely=0.3)
entrada_puerto_chico.bind("<Return>", lambda y: conf_puerto("chico",entrada_puerto_chico,entrada_ruta_bd,entrada_puerto_grande))
entrada_puerto_grande.bind("<Return>", lambda y: conf_puerto("grande",entrada_puerto_chico,entrada_ruta_bd,entrada_puerto_grande))
label_formula = ttk.Label(frame, text="Seleccionar Formula")
label_formula.place(relx=0.15, y=10)
cod = ttk.Entry(frame, width=15)
cod.place(relx=0.85, y=10)
cod_macro = ttk.Entry(frame_macro, width=15)
cod_macro.place(relx=0.85, y=10)
label_batch = ttk.Label(frame, text="N de Batch:").place(relx=0.64, y=10)
label_batchm = ttk.Label(frame_macro, text="N de Batch:").place(relx=0.64, y=10)
label_cod = ttk.Label(frame, text="Cod. Prod.:").place(relx=0.8, y=10)
label_codm = ttk.Label(frame_macro, text="Cod. Prod.:").place(relx=0.8, y=10)
nb = ttk.Entry(frame, width=15)
nb.place(relx=0.7, y=10)
nbm = ttk.Entry(frame_macro, width=15)
nbm.place(relx=0.7, y=10)
combobox = ttk.Combobox(frame, width=50, state="disable")
combobox.place(relx=0.35, y=10)

cuadro = ttk.Treeview(frame, columns=("Deposito","Cantidad"))
barra = ttk.Scrollbar(cuadro)
cuadro.column("#0", width=200, anchor="center")
cuadro.column("Cantidad", width=30, anchor="center")
cuadro.column("Deposito", width=30, anchor="center")
cuadro.heading("#0", text="MP",command=lambda: ordenar("mp"))
cuadro.heading("Cantidad", text="Cantidad")
cuadro.heading("Deposito", text="Deposito")

cuadro.config(yscrollcommand=barra.set)
barra.config(command=cuadro.yview)
cuadro.place(x=60, y=60, relwidth=0.5, relheight=0.6)
barra.place(relx=0.97, rely=0.17, relheight=0.81)
label_formula_macro = ttk.Label(frame_macro, text="Seleccionar Formula")
label_formula_macro.place(relx=0.15, y=10)
combobox_macro = ttk.Combobox(frame_macro, width=50, state="disable")
combobox_macro.place(relx=0.35, y=10)
cuadro_macro = ttk.Treeview(frame_macro, columns=("Deposito","Cantidad"))
barra_macro = ttk.Scrollbar(cuadro_macro)
cuadro_macro.column("#0", width=200, anchor="center")
cuadro_macro.column("Cantidad", width=20, anchor="center")
cuadro_macro.column("Deposito", width=20, anchor="center")
cuadro_macro.heading("#0", text="MP",command=lambda: ordenar("mp_macro"))
cuadro_macro.heading("Cantidad", text="Cantidad")
cuadro_macro.heading("Deposito", text="Deposito")
cuadro_macro.config(yscrollcommand=barra_macro.set)
barra_macro.config(command=cuadro_macro.yview)
cuadro_macro.place(x=60, y=60, relwidth=0.5, relheight=0.6)

barra_macro.place(relx=0.97, rely=0.17, relheight=0.81)
label_mp_macro = ttk.Label(frame_macro2, text="Matera Prima")
label_mp_macro.place(relx=0.12, rely=0.35)
combobox_lote_macro = ttk.Combobox(frame_macro, width=20)
combobox_lote_macro.place(relx=0.7, rely=0.25)

label_cantidad_macro = ttk.Label(frame_macro2, text="Kg")
cantidad_pesar_macro = ttk.Entry(frame_macro2, width=10, validate="key",
                        validatecommand=((frame_macro2.register(validar_entrada)), "%S"))
label_lote_macro = ttk.Label(frame_macro, text="Lote MP")
mp_selec_macro = ttk.Combobox(frame_macro2, width=20, state="disabled")
mp_selec_macro.bind("<<ComboboxSelected>>", partial(selec_materiaprima,"macro"))

label_cantidad_macro.place(relx=0.46, rely=0.35)
cantidad_pesar_macro.place(relx=0.5, rely=0.35)
label_lote_macro.place(relx=0.65, rely=0.25)
mp_selec_macro.place(relx=0.19, rely=0.35)


label_mos_macro = ttk.Label(frame_macro, text="Stock")
label_mos_macro.place(relx=0.65, rely=0.4)

mostrar_stock_macro = ttk.Entry(frame_macro, width=20)
mostrar_stock_macro.place(relx=0.7, rely=0.4)

deposito_macro_selec = ttk.Combobox(frame_macro2, width=10, state="disable")
deposito_macro_selec.bind("<<ComboboxSelected>>", partial(deposito_seleccionado,"macro"))
deposito_macro_selec.place(relx=0.36, rely=0.35)
label_deposito_macro = ttk.Label(frame_macro2, text= "Deposito")
label_deposito_macro.place(relx=0.31, rely=0.35)
label_ndebatch = ttk.Label(frame2, text="N° de Batch")
label_ndebatch.place(relx=0, rely=0.35)
n_debatch = ttk.Entry(frame2, width=7, validate="key",
                    validatecommand=((frame2.register(validar_entrada)), "%S"))
n_debatch.place(relx=0.07, rely=0.35)
label_mp = ttk.Label(frame2, text="Matera Prima")
label_mp.place(relx=0.12, rely=0.35)
combobox_lote = ttk.Combobox(frame, width=20, state="disabled")
combobox_lote.place(relx=0.7, rely=0.25)
label_cantidad = ttk.Label(frame2, text="kg")
cantidad_pesar = ttk.Entry(frame2, width=10,validate="key",
                        validatecommand=((frame2.register(validar_entrada)), "%S"))
label_lote = ttk.Label(frame, text="Lote MP")
mp_selec = ttk.Combobox(frame2, width=20, state="disabled")
deposito_selec = ttk.Combobox(frame2, width=10, state="disable")
deposito_selec.bind("<<ComboboxSelected>>", partial(deposito_seleccionado,"nucleos"))

label_cantidad.place(relx=0.5, rely=0.35)
cantidad_pesar.place(relx=0.52, rely=0.35)
label_lote.place(relx=0.65, rely=0.25)
label_mos = ttk.Label(frame, text="Stock")
label_mos.place(relx=0.65, rely=0.4)

mostrar_stock = ttk.Entry(frame, width=20)
mostrar_stock.place(relx=0.7, rely=0.4)
mp_selec.place(relx=0.19, rely=0.35)
mp_selec.bind("<<ComboboxSelected>>", partial(selec_materiaprima,"nucleos"))
deposito_selec.place(relx=0.4, rely=0.35)
label_deposito = ttk.Label(frame2, text= "Deposito")
label_deposito.place(relx=0.35, rely=0.35)
label_responsable = ttk.Label(frame2, text= "Responsable")
label_responsable.place(relx=0.6, rely=0.35)
responsable = ttk.Entry(frame2, width=20, state="disabled")
responsable.place(relx=0.66, rely=0.35)
combobox_lote.bind("<<ComboboxSelected>>", partial(selec_lote,"nucleos",mp_selec,combobox_lote_macro,mp_selec_macro,entrada_ruta_bd,combobox_lote,mostrar_stock,mostrar_stock_macro))
combobox_lote_macro.bind("<<ComboboxSelected>>", partial(selec_lote,"macro",mp_selec,combobox_lote_macro,mp_selec_macro,entrada_ruta_bd,combobox_lote,mostrar_stock,mostrar_stock_macro))


label_responsable_macro = ttk.Label(frame_macro2, text= "Responsable")
label_responsable_macro.place(relx=0.6, rely=0.35)
responsable_macro = ttk.Entry(frame_macro2, width=25, state="disabled")
responsable_macro.place(relx=0.66, rely=0.35)
label_ndebatch_macro = ttk.Label(frame_macro2, text= "N° de Batch")
label_ndebatch_macro.place(relx=0, rely=0.35)
ndebatch_macro = ttk.Entry(frame_macro2, width=5)
ndebatch_macro.place(relx=0.07, rely=0.35)
cuadro_macro2 = ttk.Treeview(frame_macro3, columns=( "Hora","N° de Batch", "MP", "Cantidad", "Lote","Vencimiento","Deposito"))
barra_macro2 = ttk.Scrollbar(cuadro_macro2)
cuadro_macro2.column("#0", width=70, anchor="w")
cuadro_macro2.column("Hora", width=70, anchor="center")
cuadro_macro2.column("N° de Batch", width=70, anchor="center")
cuadro_macro2.column("MP", width=180, anchor="center")
cuadro_macro2.column("Cantidad", width=60, anchor="center")
cuadro_macro2.column("Lote", width=150, anchor="center")
cuadro_macro2.column("Vencimiento", width=100, anchor="center")
cuadro_macro2.column("Deposito", width=100, anchor="center")
cuadro_macro2.heading("#0", text="Fecha")
cuadro_macro2.heading("Hora", text="Hora")
cuadro_macro2.heading("N° de Batch", text="N° Batch/ID",command=lambda: ordenar("batch_reg_macro",cuadro,cuadro_macro,cuadro2,cuadro_macro2))
cuadro_macro2.heading("MP", text="MP",command=lambda: ordenar("mp_macro_reg",cuadro,cuadro_macro,cuadro2,cuadro_macro2))
cuadro_macro2.heading("Cantidad", text="Cantidad")
cuadro_macro2.heading("Lote", text="lote", )
cuadro_macro2.heading("Vencimiento", text="Vencimiento", )
cuadro_macro2.heading("Deposito", text="Deposito", )
cuadro_macro2.config(yscrollcommand=barra_macro2.set)
barra_macro2.config(command=cuadro_macro2.yview)
cuadro_macro2.place(relx=0, rely=0, relwidth=0.88, relheight=1)
barra_macro2.place(relx=0.97, rely=0.11, relheight=0.85)

boton_pesar_macro = ttk.Button(frame_macro2, text="Ingresar", state="disabled")
boton_pesar_macro.place(relx=0.9, rely=0.35)

cuadro2 = ttk.Treeview(frame3, columns=("Hora", "N° de Batch", "MP", "Cantidad", "Lote","Vencimiento","Deposito"))
barra2 = ttk.Scrollbar(cuadro2)
cuadro2.column("#0", width=70, anchor="w")
cuadro2.column("N° de Batch", width=50, anchor="center")
cuadro2.column("Hora", width=70, anchor="center")
cuadro2.column("MP", width=180, anchor="center")
cuadro2.column("Cantidad", width=60, anchor="center")
cuadro2.column("Lote", width=150, anchor="center")
cuadro2.column("Vencimiento", width=100, anchor="center")
cuadro2.column("Deposito", width=100, anchor="center")
cuadro2.heading("#0", text="Fecha")
cuadro2.heading("N° de Batch", text="N° de Batch",command=lambda: ordenar("batch_reg",cuadro,cuadro_macro,cuadro2,cuadro_macro2))
cuadro2.heading("Hora", text="Hora")
cuadro2.heading("MP", text="MP",command=lambda: ordenar("mp_reg"))
cuadro2.heading("Cantidad", text="Cantidad")
cuadro2.heading("Lote", text="lote", )
cuadro2.heading("Vencimiento", text="Vencimiento", )
cuadro2.heading("Deposito", text="Deposito", )
cuadro2.config(yscrollcommand=barra2.set)
barra2.config(command=cuadro2.yview)
cuadro2.place(relx=0, rely=0, relwidth=0.88, relheight=1)
barra2.place(relx=0.97, rely=0.11, relheight=0.85)
boton_eliminar_macro = ttk.Button(frame_macro3, text="Eliminar", command=partial(eliminar,"macro",cuadro2,cod,cuadro,cuadro_macro,entrada_ruta_bd,cuadro_macro2,cod_macro))
boton_eliminar_macro.place(relx=0.91, rely=0.6)
boton_iniciar_macro = ttk.Button(frame_macro, text="Iniciar", command = partial(iniciar, "macro"), state="disable")

boton_iniciar_macro.place(relx=0.45, rely=0.9)

boton_eliminar = ttk.Button(frame3, text="Eliminar", command = partial(eliminar, "nucleos",cuadro2,cod,cuadro,cuadro_macro,entrada_ruta_bd,cuadro_macro2,cod_macro))
boton_eliminar.place(relx=0.91, rely=0.6)
comentario_macro = ttk.Entry(frame_macro3, width=20)
comentario_macro.place(relx=0.9, rely=0.1, height=80)
comentario_nucleo = ttk.Entry(frame3, width=20)
comentario_nucleo.place(relx=0.9, rely=0.1, height=80)

boton_pesar = ttk.Button(frame2, text="Pesar", command=partial(pesar,"nucleos",combobox_lote,responsable_macro,combobox_lote_macro,mp_selec_macro,cantidad_pesar_macro,cuadro_macro,responsable,n_debatch,cuadro,mp_selec,entrada_ruta_bd,cuadro_macro2,comentario_macro,ndebatch_macro,cantidad_pesar,cod_macro,deposito_macro_selec,combobox_macro,cod,deposito_selec,combobox,comentario_nucleo,cuadro2), state="disabled")
boton_pesar.place(relx=0.8, rely=0.1,relwidth=0.1, relheight=0.9)


boton1 = ttk.Button(frame, text="Iniciar",state="disable") 
boton1.configure(command = partial(iniciar, "nucleos",boton1,combobox,entrada_ruta_bd,cuadro2,cod,n_debatch,combobox_lote,cantidad_pesar,boton_pesar,responsable,combobox_macro,cuadro_macro2,boton_iniciar_macro,combobox_lote_macro,cantidad_pesar_macro,boton_pesar_macro,responsable_macro,cod_macro) )
boton1.place(relx=0.45, rely=0.9)
boton_nuevo = ttk.Button(frame, text="Nuevo", command = partial(nuevo, "nucleos",cuadro2,cuadro,boton1,combobox,cuadro_macro2,cuadro_macro,boton_iniciar_macro,combobox_macro))

boton_nuevo.place(relx=0.85, rely=0.4,relheight=0.2,relwidth=0.1)
boton_nuevo_macro = ttk.Button(frame_macro, text="Nuevo", command = partial(nuevo, "macro",cuadro2,cuadro,boton1,combobox,cuadro_macro2,cuadro_macro,boton_iniciar_macro,combobox_macro))
boton_nuevo_macro.place(relx=0.85, rely=0.4,relheight=0.2,relwidth=0.1)

#Pestaña Carga

cuadro_carga = ttk.Treeview(pestaña_carga, columns=("Formula", "CodigoProduccion"))
barra_carga = ttk.Scrollbar(cuadro_carga)
cuadro_carga.column("#0", width=70, anchor="w")
cuadro_carga.column("Formula", width=50, anchor="center")
cuadro_carga.column("CodigoProduccion", width=50, anchor="center")
cuadro_carga.heading("#0", text="N° de Nucleo")
cuadro_carga.heading("Formula", text="Furmula")
cuadro_carga.heading("CodigoProduccion", text="CodigoProduccion")
cuadro_carga.config(yscrollcommand=barra_carga.set)
barra_carga.config(command=cuadro_carga.yview)
cuadro_carga.place(relx=0.2, rely=0.1, relwidth=0.3, relheight=0.3)
barra_carga.place(relx=0.945, rely=0.13, relheight=0.85)
cuadro_carga2 = ttk.Treeview(pestaña_carga, columns=("Hora", "N° de Batch","N° de Nucleo", "Formula", "CodigoProduccion","CodNucleo"))
barra_carga2 = ttk.Scrollbar(cuadro_carga2)
cuadro_carga2.column("#0", width=70, anchor="w")
cuadro_carga2.column("Hora", width=70, anchor="center")
cuadro_carga2.column("N° de Batch", width=50, anchor="center")
cuadro_carga2.column("N° de Nucleo", width=50, anchor="center")
cuadro_carga2.column("Formula", width=180, anchor="center")
cuadro_carga2.column("CodigoProduccion", width=50, anchor="center")
cuadro_carga2.column("CodNucleo", width=50, anchor="center")
cuadro_carga2.heading("#0", text="Fecha")
cuadro_carga2.heading("Hora", text="Hora")
cuadro_carga2.heading("N° de Batch", text="N° de Batch")
cuadro_carga2.heading("N° de Nucleo", text="N° de Nucleo")
cuadro_carga2.heading("Formula", text="Formula")
cuadro_carga2.heading("CodigoProduccion", text="CodigoProduccion" )
cuadro_carga2.heading("CodNucleo", text="CodNucleo", )
cuadro_carga2.config(yscrollcommand=barra_carga2.set)
barra_carga2.config(command=cuadro_carga2.yview)
cuadro_carga2.place(relx=0.05, rely=0.5, relwidth=0.8, relheight=0.5)
barra_carga2.place(relx=0.98, rely=0.11, relheight=0.85)
boton_actualizar = ttk.Button(pestaña_carga, text="Actualizar", command= partial(actualizar,entrada_ruta_bd,cuadro_carga))
boton_actualizar.place(relx=0.8, rely=0.12, relheight=0.1, relwidth=0.1)

boton_eliminarcarga = ttk.Button(pestaña_carga, text="Eliminar", command=partial(eliminar_carga,cuadro_carga2,entrada_ruta_bd,cuadro_carga))
boton_eliminarcarga.place(relx=0.87, rely=0.7, relheight=0.1, relwidth=0.1)
label_formula_carga = ttk.Label(pestaña_carga, text="Seleccionar Formula")
label_formula_carga.place(relx=0.2, rely=0.02)
combobox_carga = ttk.Combobox(pestaña_carga, width=50)
combobox_carga.place(relx=0.3, rely=0.02)


label_carga_ndebatch = ttk.Label(pestaña_carga, text="N° de Batch")
label_carga_ndebatch.place(relx=0.72, rely=0.02)
ndebatch_carga= ttk.Entry(pestaña_carga,width=5)
ndebatch_carga.place(relx=0.8, rely=0.02)
label_comentario_nucleos= ttk.Label(frame3,text="Comentario")
label_comentario_nucleos.place(relx=0.91, rely=0.01)

label_comentario_macro= ttk.Label(frame_macro3,text="Comentario")
label_comentario_macro.place(relx=0.91, rely=0.01)

label_comentario_carga= ttk.Label(pestaña_carga,text="Comentario")
label_comentario_carga.place(relx=0.62, rely=0.15)
comentario_carga = ttk.Entry(pestaña_carga, width=40)
comentario_carga.place(relx=0.55, rely=0.19, height=80)
label_sector= ttk.Label(pestaña_config,text="Sector")
label_sector.place(relx=0.06, rely=0.6)
sele_sector = ttk.Combobox(pestaña_config, width=20,values=["Cereales","Jarabe","Comasa"])
sele_sector.place(relx=0.27, rely=0.6)

combobox.bind("<<ComboboxSelected>>", partial(formula_seleccionada,"nucleos",entrada_ruta_bd,cod,cuadro,cod_macro,cuadro_macro,ndebatch_carga,cuadro_carga2,combobox,combobox_macro,combobox_carga,nb,nbm))
boton_cargar = ttk.Button(pestaña_carga, text="Cargar", command= partial(cargar,combobox_carga,cuadro_carga,comentario_carga,entrada_ruta_bd,cuadro_carga2))
boton_cargar.place(relx=0.8, rely=0.27, relheight=0.1, relwidth=0.1)
combobox_macro.bind("<<ComboboxSelected>>", partial(formula_seleccionada,"macro",entrada_ruta_bd,cod,cuadro,cod_macro,cuadro_macro,ndebatch_carga,cuadro_carga2,combobox,combobox_macro,combobox_carga,nb,nbm))
boto_autenticar = ttk.Button(frame_config, text="Autenticar", command=partial(autenticar,entrada_contraseña,boton_pesar,deposito_selec,deposito_macro_selec,mp_selec,combobox_lote,boton_pesar_macro,mp_selec_macro,combobox_lote_macro,sele_sector,boton_ruta_bd,entrada_ruta_bd,entrada_puerto_grande,entrada_puerto_chico))
boto_autenticar.place(relx=0.8, rely=0.01)
combobox_carga.bind("<<ComboboxSelected>>", partial(formula_seleccionada,"carga",entrada_ruta_bd,cod,cuadro,cod_macro,cuadro_macro,ndebatch_carga,cuadro_carga2,combobox,combobox_macro,combobox_carga))
ventana.title(sector_nucleos)
boton_iniciar_macro.configure(command = partial(iniciar, "macro",boton1,combobox,entrada_ruta_bd,cuadro2,cod,n_debatch,combobox_lote,cantidad_pesar,boton_pesar,responsable,combobox_macro,cuadro_macro2,boton_iniciar_macro,combobox_lote_macro,cantidad_pesar_macro,boton_pesar_macro,responsable_macro,cod_macro))
cuadro_macro.bind("<<TreeviewSelect>>",partial(mp_seleccionada,"macro",cuadro,entrada_ruta_bd,deposito_selec,mp_selec,combobox_lote,cantidad_pesar,n_debatch,cuadro_macro,deposito_macro_selec,mp_selec_macro,combobox_lote_macro,cantidad_pesar_macro,ndebatch_macro,mostrar_stock,mostrar_stock_macro))

boton_pesar_macro.configure(command=partial(pesar,"macro",combobox_lote,responsable_macro,combobox_lote_macro,mp_selec_macro,cantidad_pesar_macro,cuadro_macro,responsable,n_debatch,cuadro,mp_selec,entrada_ruta_bd,cuadro_macro2,comentario_macro,ndebatch_macro,cantidad_pesar,cod_macro,deposito_macro_selec,combobox_macro,cod,deposito_selec,combobox,comentario_nucleo,cuadro2))
sele_sector.bind("<<ComboboxSelected>>", partial(seleccionar_sector,sele_sector,ruta_base,ruta_sector,entrada_ruta_bd))


cuadro.heading("#0",command=partial(ordenar,"batch",cuadro,cuadro_macro,cuadro2,cuadro_macro2))
#cuadro.heading("MP",command=partial(ordenar,"mp",cuadro,cuadro_macro,cuadro2,cuadro_macro2))
cuadro2.heading("MP",command=partial(ordenar,"mp_reg",cuadro,cuadro_macro,cuadro2,cuadro_macro2))
#cuadro_macro.heading("MP",command=partial(ordenar,"mp_macro",cuadro,cuadro_macro,cuadro2,cuadro_macro2))
cuadro_macro.heading("#0",command=partial(ordenar,"batch_macro",cuadro,cuadro_macro,cuadro2,cuadro_macro2))
cuadro.bind("<<TreeviewSelect>>",partial(mp_seleccionada,"nucleos",cuadro,entrada_ruta_bd,deposito_selec,mp_selec,combobox_lote,cantidad_pesar,n_debatch,cuadro_macro,deposito_macro_selec,mp_selec_macro,combobox_lote_macro,cantidad_pesar_macro,ndebatch_macro,mostrar_stock,mostrar_stock_macro))

leer_archivo(ruta_base,ruta_sector,entrada_ruta_bd,sele_sector)
leer_base(entrada_ruta_bd,sele_sector,combobox,combobox_carga,combobox_macro,entrada_puerto_chico,entrada_puerto_grande,des_balanza_grande,desactivar_balanza_chica,boton_ruta_bd)

ventana.mainloop()

